### PR TITLE
Guide - Part 2

### PR DESCRIPTION
**Pull request by js150422**
my discord name: jane08
my homeword page:  
http://18.210.228.7:3000/

Thank you

### CODE REVIEW

**Comment by cwpeng** [comment]
Almost done, but font size of 約定行程, 登入註冊, attract infos are too small. Fix them and leave comment for me to review again.

**Comment by js150422** [comment]
Dear Teacher:
I fix css my font size of 約動行程，登入註冊 from 13.3 to 16.
Thank you.

**Comment by cwpeng** [comment]
Font size of attraction information text is too small, as well.

**Comment by js150422** [comment]
I fix css my font size of attraction font-szie from 13.3 to 16.

Thank you.

**Comment by js150422** [comment]
(≧д≦ヾ)

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by js150422** [comment]
sorry I miss my attraction font-color
I fix it done.
Thank you.

**Pull request merged**
