### PR TITLE
Guide - Part 7

### PR DESCRIPTION
**Pull request by js150422**
Dear Teacher:

I'm YiJen
discord name: jane08
part7-1~part7-7 complete

Thank you :)

http://18.210.228.7:3000/

### CODE REVIEW

**Comment by cwpeng** [comment]
Yon have done many good details. But we should remove booking data after successful ordering.

**Comment by js150422** [comment]
Dear~Teacher

I fixed my booking page and kill attraction page blank : )

http://18.210.228.7:3000/

Thank you

**Comment by cwpeng** [comment]
After I sign in failed, I cannot click 點此註冊, and change to sign up form immediately. And we don't need to refresh page after unsuccessful signing in.

Try to smooth your sign in/sign up flow in every possible operations.

**Comment by js150422** [comment]
I try  sign in/sign up flow.
and repair signup page.

**Comment by js150422** [comment]
but I sorry about reset database.
you need to signup again.

**Comment by js150422** [comment]
I find my ordertime is UTC and change it to GTM.

**Comment by cwpeng** [comment]
OK. Much Better. :)

**Comment by js150422** [comment]
May I merge to main ?😊

**Review by cwpeng — APPROVED** [review]
OK. Sorry for forgetting to approve your request.

**Pull request merged**
