### PR TITLE
第二階段 Guide - Part 1

### PR DESCRIPTION
**Pull request by js150422**
姓名: 蔡宜珍
Discord: jane08

Issues had repaired":
1.fixed(change Change loop logic)
http://18.210.228.7:3000/api/attractions?page=4
http://18.210.228.7:3000/api/attractions?page=0&keyword=%E8%97%9D%E8%A1%93

2.fixed(change Change loop logic)
http://18.210.228.7:3000/api/attractions?page=6

3.Img is fixed about one attraction url.

### CODE REVIEW

**Comment by js150422** [comment]
conflict resolution

**Review by cwpeng — CHANGES_REQUESTED** [review]
We should use LIMIT statement in SQL query to do range selection. We never get all data at once, it's unacceptable.

I mean code below should be replaced by LIMIT query, and you have to change any related code to make it work.
```
		if keyword!=None:
			sql="SELECT * FROM attractions WHERE name LIKE '%s' ORDER BY `id`"%("%"+keyword+"%")
		else:
			sql="SELECT * FROM attractions ORDER BY `id`"
		cursor.execute(sql)
		result = cursor.fetchall()
```

You don't need to close pull request, just create new commits, and request me review again from right side of this page.

**Comment by js150422** [comment]
fix SQL query
 USE Count and Limit^^

**Comment by cwpeng** [comment]
Request me review again from right side of this page.

**Comment by cwpeng** [comment]
Not assignee. Re-request review.

**Review by js150422 — COMMENTED** [review]
create new commits

**Comment by cwpeng** [comment]
Just check reviewer section on this page carefully, there is a clickable icon you can re-request me review.

**Review by cwpeng — CHANGES_REQUESTED** [review]
Almost done but final issue.

Let's check searching results of keyword 館. Because page 1 have data, http://18.210.228.7:3000/api/attractions?page=1&keyword=%E9%A4%A8, your "nextPage" of page 0, http://18.210.228.7:3000/api/attractions?page=0&keyword=%E9%A4%A8, should be 1, not null.

**Comment by cwpeng** [comment]
Additional issue: http://18.210.228.7:3000/api/attraction/5 is broken. I guess it's due to loss of your database connection.

**Review by cwpeng — APPROVED** [review]
OK. Well Done.

**Pull request merged**
