### PR TITLE
Guide_-_Part_5

### PR DESCRIPTION
**Pull request by js150422**
Dear Teacher:
I'm YiJen
discord name:  jane08

my home work:
http://18.210.228.7:3000/
http://18.210.228.7:3000/attraction/23
http://18.210.228.7:3000/booking

Thank you :)

### CODE REVIEW

**Comment by js150422** [comment]
Dear Teacher:

I repair page  redirect and set cursor style.

Thank you :)

**Comment by cwpeng** [comment]
Layout issues. Always keep attention on details, it's what we will ignored but represent potential quality of a person.

未命名-4

**Comment by js150422** [comment]
Dear Teacher:

I repair page layout and

Thank a lot :)

**Comment by cwpeng** [comment]
I see this. If token is invalid (maybe expired), we should treat it as a not signed in user and redirect to home page.

未命名-4

**Comment by js150422** [comment]
Dear Teacher:

I repair page  expired page  redirect

Thank  :)

**Review by cwpeng — APPROVED** [review]
OK. Done.

**Comment by js150422** [comment]
Thank you:)

**Pull request merged**
